window.PROJECT_DETAILS = {
  "solarbot": {
    metrics: [["%85", "Otonom Çalışma"], ["%95+", "Algılama Doğruluğu"], ["OAK-D", "Derinlik Kamera"]],
    summary: "85%+ otonom çalışma oranı elde eden güneş paneli temizleme robotu; engel tespiti için derinlik kameraları, SLAM ile navigasyon ve harita oluşturma, %95+ doğrulukla YOLO tabanlı panel tespiti ve insan takip yetkinliği. Smart BMS entegre pil sistemi.",
    body: [
      ["Ne Yaptım", "Gerçek zamanlı engel tespiti ve kaçınma için OAK-D derinlik kameraları kullanan otonom navigasyon sistemi geliştirdim. SLAM algoritmaları çevre haritalarını oluştururken robot navigasyonunu sağlıyor. YOLOv5/v8 kullanan görüntü işleme hattı güneş panellerini %95+ doğrulukla tespit ediyor. Flutter mobil uygulama gerçek zamanlı telemetri ve uzaktan kontrol sunuyor; Smart BMS güç dağıtımını ve izlemeyi yönetiyor."],
      ["Canlı Simülasyon Halefi: Robot Sim", "Projenin devamı olarak aynı otonomi yaklaşımını depo temalı tam bir simülasyona taşıdım: ROS 2 Humble + Gazebo üzerinde paletli bir robot, üzerinde 6 eksenli UR5e kol ve gripper ile tamamen otonom nesne toplama-taşıma (pick & place) yapıyor. Nav2 otonom sürüş, gerçek zamanlı doluluk haritalama, OpenCV nesne tanıma, görev kuyruğu, batarya modeli ve otonom şarj istasyonu içeriyor. Kontrol merkezi telefona kurulabilen bir PWA; ayrıca Oculus Quest 2 ile WebXR üzerinden deponun dijital ikizi içinde robotu VR'da sürmek ve kola hedef vermek mümkün. Tamamı tek WebSocket üzerinden, şifre korumalı bir Tailscale adresinde yayınlanıyor."]
    ],
    tech: [["Donanım", ["Jetson Nano/Orin", "OAK-D Kamera", "Smart BMS"]], ["Görüntü İşleme", ["Python", "OpenCV", "YOLOv5/v8", "SLAM"]], ["İletişim", ["RS-485", "UDP"]], ["Yazılım", ["Flutter", "Linux"]]],
    highlights: [["Otonom Navigasyon", "OAK-D derinlik kameralarıyla gerçek zamanlı engel tespiti ve SLAM tabanlı haritalama."], ["Görüntü İşleme", "Farklı saha koşullarında %95+ doğrulukla panel tespiti yapan YOLOv5/v8 hattı."], ["Mobil Kontrol", "Gerçek zamanlı telemetri ve uzaktan kontrol için Flutter uygulaması."], ["İnsan Takibi", "Manuel yönlendirme modunda kişi takip yetkinliği."]],
    results: [["Performans Göstergeleri", ["Gerçek dünya koşullarında %85 otonom çalışma", "Tüm senaryolarda %95+ panel algılama doğruluğu", "Smart BMS ile pil sistemi entegrasyonu", "OAK-D ile engel tespiti", "Flutter izleme ve kontrol uygulaması"]], ["İş Etkisi", ["Manuel temizleme ihtiyacının ortadan kalkmasıyla işgücü maliyeti azaldı", "Düzenli temizlikle panel verimi arttı", "İşçiler tehlikeli yüksekliklerden uzaklaştırıldı", "Her ölçekte güneş çiftliğine uygulanabilir çözüm"]]],
    gallery: [{"src":"images/projects/solarbot-01.jpg","label":"SB-F01"},{"src":"images/projects/solarbot-02.jpg","label":"SB-F02"},{"src":"images/projects/solarbot-img-01.jpg","label":"SB-F03"},{"src":"images/projects/solarbot-img-02.jpg","label":"SB-F04"},{"src":"images/projects/solarbot-img-04.jpg","label":"SB-F05"},{"src":"images/projects/solarbot-img-05.jpg","label":"SB-F06"},{"src":"images/projects/solarbot-img-06.jpg","label":"SB-F07"},{"src":"images/projects/solarbot-img-07.jpg","label":"SB-F08"}],
    videos: [{"src":"https://kaankirsan.github.io/images/projects/solarbot-video-01.mp4","poster":"images/projects/solarbot-video-01-poster.jpg","label":"SB-V01"},{"src":"https://kaankirsan.github.io/images/projects/solarbot-video-02.mp4","poster":"images/projects/solarbot-video-02-poster.jpg","label":"SB-V02"},{"src":"https://kaankirsan.github.io/images/projects/solarbot-video-03_compressed.mp4","poster":"images/projects/solarbot-video-03_compressed-poster.jpg","label":"SB-V03"}],
    // Canli simulasyon demosu. Bu blok yalniz bu projede var; index.html
    // icindeki bolum <sc-if detail.hasSim> ile sarili, diger projelerde cizilmez.
    sim: {
      intro: "Projenin canli simulasyon halefi Robot Sim: ROS 2 + Gazebo uzerinde depo temali sahada paletli robot + 6 eksenli UR5e kol. Tarayicidan surulur, haritaya tiklanarak otonom hedef verilir, nesne secilip tam otonom pick & place gorevi baslatilir; Oculus Quest 2 ile deponun dijital ikizi icinde VR kontrol de mumkun. Asagidaki adresler canli sistemden yayin yapar.",
      note: "Canli demo yalnizca belirli saatlerde aciktir. Adresler yanit vermiyorsa demo o an kapali demektir; randevu icin iletisime gecebilirsiniz.",
      password: "1234",
      links: [
        {
          label: "Kontrol Merkezi (PWA)",
          desc: "Cift joystickli surus ekrani, canli on + bilek kamerasi, gercek zamanli harita (hedef isareti + rota), robot kol kontrol sayfasi ve otonom gorev kuyrugu.",
          url: "https://acer.tail6be8c.ts.net:8443/"
        },
        {
          label: "VR - Oculus Quest 2 (WebXR)",
          desc: "Deponun dijital ikizi icinde dur, robotu cubuklarla sur, kolu tut-surukle-birak ile hedefe gonder. PC tarayicisinda duz 3B onizleme olarak da acilir.",
          url: "https://acer.tail6be8c.ts.net:8443/vr.html"
        },
        {
          label: "Gazebo - 3B Simulasyon",
          desc: "Depo sahasi: raflar, platformlar, tasinabilir nesneler, sarj istasyonu ve robot. Fizik motoru gercek zamanli.",
          url: "https://acer.tail6be8c.ts.net:8443/goruntu"
        },
        {
          label: "RViz2 - Harita ve Navigasyon",
          desc: "Gercek zamanli doluluk haritasi, costmap katmanlari, nokta bulutu ve lazer taramasi.",
          url: "https://acer.tail6be8c.ts.net:8443/harita"
        }
      ],
      stack: ["ROS 2 Humble", "Gazebo Classic 11", "Nav2", "UR5e 6 eksen kol", "Gercek zamanli haritalama", "WebXR (Quest 2)", "WSL2 / Ubuntu 22.04"]
    }
  },
  "container": {
    metrics: [["5000+", "Satır Kod"], ["Gerçek Zaman", "Veri İzleme"], ["iOS + Android", "Çok Platform"]],
    summary: "Güneş konteyner izleme ve kontrolü için Flutter çapraz platform uygulaması. PLC ile Modbus TCP iletişimi, çoklu sensör entegrasyonu, gerçek zamanlı veri işleme, otomatik karar verme ve istatistiksel analiz içeren üretim raporlama.",
    body: [
      ["Zorluk", "Güneş konteyner sistemleri optimal performans, güvenlik ve verimlilik için sürekli izleme gerektirir. Operatörlerin sahada bulunmadan kritik parametrelere erişmesi, acil durumları yönetmesi ve üretime her an hâkim olması gerekiyordu."],
      ["Çözüm", "Modbus TCP üzerinden doğrudan PLC ile haberleşen kapsamlı bir Flutter uygulaması geliştirdim: tüm parametrelerin gerçek zamanlı izlenmesi, uzaktan kontrol, acil durum yönetimi, hava durumu entegrasyonu ve analitik paneli."],
      ["Teknik Yaklaşım", "Mimari, endüstriyel PLC sistemleriyle konuşan güçlü bir Modbus TCP istemcisi üzerine kurulu. Bulut API entegrasyonu veri kalıcılığı, tarihsel eğilim analizi ve rol tabanlı çok kullanıcılı erişim sağlıyor; acil senaryo yönetimi anlık uyarı ve uzaktan kapatma imkânı veriyor."]
    ],
    tech: [["Mobil", ["Flutter", "Dart", "Durum Yönetimi"]], ["Endüstriyel İletişim", ["Modbus TCP", "PLC Entegrasyonu", "Gerçek Zamanlı Veri"]], ["Backend & Bulut", ["Cloud API", "Hava Durumu Entegrasyonu", "Otomatik Uyarılar"]], ["Veri", ["Yerel Depolama", "Önbellekleme", "Rapor Üretimi"]]],
    highlights: [["Gerçek Zamanlı İzleme", "Enerji üretimi, pil durumu, inverter performansı ve çevre koşullarının canlı görselleştirmesi."], ["Modbus TCP Entegrasyonu", "Ara sunucu olmadan PLC ile doğrudan, güvenilir veri alışverişi ve komut gönderimi."], ["Acil Durum Yönetimi", "Kritik olaylarda anlık uyarı ve uzaktan acil kapatma."], ["Hava Durumu Entegrasyonu", "Üretim planlamasını optimize etmek için gerçek zamanlı hava verisi ve tahmin."]],
    results: [["Teknik Başarılar", ["5000+ satır üretim kalitesinde Dart kodu", "Gerçek zamanlı Modbus TCP iletişimi", "Çoklu sensör veri toplama ve otomatik karar verme", "İstatistiksel analiz ve üretim raporlama"]], ["Operasyonel Faydalar", ["Uzaktan izleme ile tesiste bulunma zorunluluğu kalktı", "Hızlı acil durum yanıtıyla kesinti ve hasar azaldı", "Tarihsel veriyle performans optimizasyonu", "Çok kullanıcı desteğiyle takım koordinasyonu"]]],
    gallery: [{"src":"images/projects/container-01.jpg","label":"KNT-F01"},{"src":"images/projects/container-02.jpg","label":"KNT-F02"},{"src":"images/projects/container-img-01.jpg","label":"KNT-F03"},{"src":"images/projects/container-img-02.jpg","label":"KNT-F04"},{"src":"images/projects/container-img-03.jpg","label":"KNT-F05"},{"src":"images/projects/container-img-04.png","label":"KNT-F06"},{"src":"images/projects/container-img-05.png","label":"KNT-F07"},{"src":"images/projects/container-img-06.png","label":"KNT-F08"},{"src":"images/projects/container-img-07.png","label":"KNT-F09"},{"src":"images/projects/container-img-08.png","label":"KNT-F10"},{"src":"images/projects/container-img-09.png","label":"KNT-F11"},{"src":"images/projects/container-img-10.png","label":"KNT-F12"},{"src":"images/projects/container-img-11.png","label":"KNT-F13"},{"src":"images/projects/container-img-12.png","label":"KNT-F14"},{"src":"images/projects/container-img-13.png","label":"KNT-F15"},{"src":"images/projects/container-img-14.png","label":"KNT-F16"}],
    videos: [{"src":"https://kaankirsan.github.io/images/projects/container-video-01.mp4","poster":"images/projects/container-video-01-poster.jpg","label":"KNT-V01"},{"src":"https://kaankirsan.github.io/images/projects/container-video-02.mp4","poster":"images/projects/container-video-02-poster.jpg","label":"KNT-V02"}]
  },
  "testing": {
    metrics: [["0.0001", "L/dak Akış Hassasiyeti"], ["0.01", "bar Basınç Hassasiyeti"], ["ATEX", "Patlama Korunmalı"]],
    summary: "Siemens PLC ve Profinet iletişimiyle WinCC Unified HMI kullanan jet yakıtı test ünitesi. Orantılı valflerle PID kontrol sayesinde 0.0001 L/dak ve 0.01 bar hassasiyet; yangın riski tespiti ve patlama korunmalı sertifikalı bileşenler.",
    body: [
      ["Ne Yaptım", "Profinet üzerinden Siemens PLC ile haberleşen WinCC Unified web ve yerel arayüzünü kurdum. Akış ve basınç için yüksek hassasiyetli sensörleri entegre ettim; orantılı valflerle PID kontrol geliştirerek 0.0001 L/dak ve 0.01 bar hassasiyet sağladım."],
      ["Güvenlik", "Yangın riski tespit ve koruma sistemleri uyguladım. Tüm sensörler ve kontrol panelleri tehlikeli ortamda güvenli çalışma için patlama korunmalı sertifikalıdır."]
    ],
    tech: [["Kontrol", ["Siemens PLC", "WinCC Unified", "TIA Portal", "PID Kontrol"]], ["İletişim", ["Profinet", "Endüstriyel Ağlar"]], ["Sensörler", ["Unimass Akış Sensörü", "Basınç Sensörleri", "Orantılı Valfler"]], ["Güvenlik", ["Patlama Korunmalı", "Yangın Tespiti", "ATEX"]]],
    highlights: [["Hassas Akış Kontrolü", "Orantılı valfleri düzenleyen, 0.0001 L/dak hassasiyet sağlayan PID algoritmaları."], ["Basınç Yönetimi", "0.01 bar doğrulukla yüksek hassasiyetli basınç kontrolü."], ["WinCC Unified HMI", "Profinet üzerinden izleme, kontrol ve veri görselleştirme için web + yerel arayüz."], ["Patlama Korunmalı Tasarım", "Tehlikeli yakıt test ortamı için sertifikalı sensör ve panolar."]],
    results: [["Teknik Başarılar", ["0.0001 L/dak akış ölçüm hassasiyeti", "0.01 bar basınç kontrol doğruluğu", "Orantılı valf düzenleme için PID kontrol", "Yangın tespit ve koruma sistemleri"]], ["Sistem Yetkinlikleri", ["Yerel ve uzaktan çalışma için WinCC Unified HMI", "Siemens PLC ile Profinet iletişimi", "Unimass akış sensörü entegrasyonu", "Gerçek zamanlı veri kaydı ve eğilim analizi"]]],
    gallery: [{"src":"images/projects/testing-01.jpg","label":"JYT-F01"},{"src":"images/projects/testing-img-01.png","label":"JYT-F02"},{"src":"images/projects/testing-img-02.png","label":"JYT-F03"},{"src":"images/projects/testing-img-03.png","label":"JYT-F04"},{"src":"images/projects/testing-img-04.png","label":"JYT-F05"},{"src":"images/projects/testing-img-05.png","label":"JYT-F06"},{"src":"images/projects/testing-img-06.png","label":"JYT-F07"},{"src":"images/projects/testing-img-07.png","label":"JYT-F08"},{"src":"images/projects/testing-img-08.png","label":"JYT-F09"},{"src":"images/projects/testing-img-09.png","label":"JYT-F10"}],
    videos: []
  },
  "welding": {
    metrics: [["%35", "Duruş Azaltımı"], ["%40", "Verimlilik Artışı"], ["S7-1200", "Siemens PLC"]],
    summary: "Kaynak robotu ile hassas konumlandırıcı entegrasyonu: gerçek zamanlı konum geri beslemesi, PID otomatik ayarlama, güvenlik kilitleri ve kapsamlı HMI. Plansız duruş %35 azaldı, üretim verimi %40 arttı.",
    body: [
      ["Ne Yaptım", "Siemens S7-1200 PLC kullanan kaynak robotunu hassas konumlandırıcıyla entegre ettim. Robot kontrolü için kuru röle iletişimi, Profinet ve Modbus RS-485 üzerinden Veichi SD700 servo sürücülerle gerçek zamanlı konum geri beslemesi kurdum. PID otomatik ayarlama, güvenlik kilitleri ve acil durdurma mantığı ile alarm kaydı içeren HMI geliştirdim."]
    ],
    tech: [["PLC", ["Siemens S7-1200", "TIA Portal"]], ["Sürücüler", ["Veichi SD700", "PID Kontrol"]], ["İletişim", ["Profinet", "Modbus", "RS-485"]], ["Robot", ["Kaynak Robotu", "Kuru Röle"]]],
    highlights: [["Hassas Motor Kontrolü", "Konum geri beslemesi, hız profilleme ve moment sınırlamayla tutarlı kaynak kalitesi."], ["Robot Koordinasyonu", "Senkronize hareket kontrolü ve koordineli çalışma alanı yönetimi."], ["Kestirimci Bakım", "Servo performansını izleyip anormallikleri yakalayan algoritmalarla plansız duruş %35 azaldı."], ["Güvenlik Entegrasyonu", "Acil durdurma, ışık perdesi, güvenlik kilidi ve iki el kontrolü içeren tam güvenlik devresi."]],
    results: [["Performans İyileştirmeleri", ["Üretim veriminde %40 artış", "Kaynak çevrim sürelerinde %25 azalma", "Plansız duruşta %35 azalma", "Kaynak kalitesinde tutarlılık"]], ["Teknik Teslimler", ["5000+ satır mantık içeren tam PLC programı", "30+ ekranlı kapsamlı HMI", "Ayrıntılı elektriksel şemalar ve dokümantasyon", "Operatör eğitim materyalleri ve bakım prosedürleri"]]],
    gallery: [{"src":"images/projects/welding-01.jpg","label":"KYN-F01"},{"src":"images/projects/welding-02.jpg","label":"KYN-F02"},{"src":"images/projects/welding-img-01.jpg","label":"KYN-F03"},{"src":"images/projects/welding-img-02.jpg","label":"KYN-F04"}],
    videos: [{"src":"https://kaankirsan.github.io/images/projects/welding-video-01.mp4","poster":"images/projects/welding-video-01-poster.jpg","label":"KYN-V01"},{"src":"https://kaankirsan.github.io/images/projects/welding-video-02.mp4","poster":"images/projects/welding-video-02-poster.jpg","label":"KYN-V02"}]
  },
  "warehouse": {
    metrics: [["500+", "I/O Noktası"], ["3", "Tesis"], ["%99.5", "Çalışma Oranı"]],
    summary: "Üç ayrı üretim tesisinde konveyör otomasyon sistemleri kuruldu. 500+ I/O noktası ve 20 AC sürücü için Modbus iletişimi yapılandırıldı; iş gücü verimi iki katına çıkarıldı.",
    body: [["Ne Yaptım", "Üç tesiste 500+ I/O noktası ve 20 AC sürücü için kapsamlı Modbus yapılandırmasıyla konveyör otomasyonu programladım. Modbus RS-485 ile AC sürücü haberleşmesi kurdum, iş gücü verimini ikiye katlayan otomatik taşıma iş akışı geliştirdim. Siemens PLC ve TIA Portal ile hareket sekansı ve kontrol mantığını yazdım; HMI ile sistem durumu ve performans izlemesi ekledim."]],
    tech: [["Kontrol", ["Siemens PLC", "TIA Portal", "Kontrol Mantığı"]], ["İletişim", ["Modbus RS-485", "AC Sürücü Haberleşme", "500+ I/O"]], ["Sürücüler", ["20 AC Sürücü", "Hız Kontrolü", "Motor Yönetimi"]], ["İzleme", ["HMI", "Sistem Durumu", "Performans Analizi"]]],
    highlights: [["Çok Tesis Yönetimi", "Üç tesiste birbirine bağlı konveyör otomasyonu, koordineli iş akışı ve merkezi izleme."], ["Modbus İletişimi", "20 AC sürücüyle güvenilir RS-485 haberleşmesi ve 500+ I/O noktasında kesintisiz veri akışı."], ["Otomatik İş Akışı", "El müdahalesini azaltan otomatik taşıma prosesi, hata yönetimi ve güvenlik kilitleri."], ["Yüksek Çalışma Oranı", "Kestirimci bakım ve hata tespitiyle %99.5+ sistem çalışma oranı."]],
    results: [["Operasyonel Faydalar", ["İş gücü veriminde 2x artış", "El müdahalesinde belirgin azalma", "%99.5+ sistem çalışma oranı", "Taşıma hatalarında azalma"]], ["Teknik Başarılar", ["500+ I/O noktası yönetimi", "20 AC sürücüyle Modbus haberleşmesi", "Üç tesisi kapsayan entegre sistem", "Kapsamlı HMI ve izleme"]]],
    gallery: [{"src":"images/projects/warehouse-img-01.jpg","label":"KNV-F01"},{"src":"images/projects/warehouse-img-02.jpg","label":"KNV-F02"},{"src":"images/projects/warehouse-img-03.jpg","label":"KNV-F03"},{"src":"images/projects/warehouse-img-04.png","label":"KNV-F04"}],
    videos: [{"src":"https://kaankirsan.github.io/images/projects/warehouse-video-01.mp4","poster":"images/projects/warehouse-video-01-poster.jpg","label":"KNV-V01"}]
  },
  "mobile-target": {
    metrics: [["SIL 2", "Sertifika"], ["2 Eksen", "Hareket Kontrolü"], ["Gerçek Zaman", "SCADA İzleme"]],
    summary: "Excel entegre WinCC SCADA sistemi ile servo motor destekli çift eksen hareket kontrolü; arayıcı başlık testleri için güvenlik sınırları, acil durdurma ve SIL 2 sertifikalı güvenlik devreleri.",
    body: [["Ne Yaptım", "Arayıcı başlık testleri için çift eksen servo motor kontrolü kullanan hareketli hedef sistemi geliştirdim. Excel uyumlu hareket profilleri oluşturup WinCC SCADA ile bağladım. Güvenlik sınırları ve acil durdurma ile operatör güvenliğini, SIL 2 sertifikalı güvenlik devreleriyle sistem korumasını sağladım."]],
    tech: [["Hareket Kontrolü", ["Servo Motorlar", "Çift Eksen", "Servo Sürücüler"]], ["SCADA", ["WinCC", "Gerçek Zamanlı İzleme", "Excel Entegrasyonu"]], ["Güvenlik", ["SIL 2", "Acil Durdurma", "Güvenlik Kilitleri"]], ["PLC", ["Kontrol Mantığı", "Güvenli I/O", "Hareket Planlama"]]],
    highlights: [["Hassas Hareket Kontrolü", "Excel entegre hareket profilleriyle test gereksinimlerine uyarlanan çift eksen servo kontrol."], ["SCADA İzleme", "WinCC üzerinden sistem durumu, konum geri beslemesi ve tüm operasyonların kaydı."], ["SIL 2 Güvenlik", "Sertifikalı güvenlik devreleri, acil durdurma ve hareket sınırları."], ["Excel Entegrasyonu", "Test planlarının Excel'den doğrudan yüklenmesiyle hızlı senaryo oluşturma."]],
    results: [["Sistem Yetkinlikleri", ["Çift eksen servo hareket kontrolü", "Excel entegre hareket profilleri", "WinCC SCADA gerçek zamanlı izleme", "SIL 2 sertifikalı güvenlik sistemi"]], ["Operasyonel Etki", ["Test prosedürlerinde doğruluk ve tekrarlanabilirlik", "Excel uyumlu planlarla hız kazancı", "En üst düzeyde operatör güvenliği", "Düzenleyici gereksinimlerle tam uyum"]]],
    gallery: [{"src":"images/projects/mobile-target-img-01.jpg","label":"HDF-F01"},{"src":"images/projects/mobile-target-img-02.png","label":"HDF-F02"},{"src":"images/projects/mobile-target-img-03.png","label":"HDF-F03"},{"src":"images/projects/mobile-target-img-04.png","label":"HDF-F04"},{"src":"images/projects/mobile-target-img-05.png","label":"HDF-F05"},{"src":"images/projects/mobile-target-img-06.png","label":"HDF-F06"},{"src":"images/projects/mobile-target-img-07.png","label":"HDF-F07"}],
    videos: []
  },
  "wagon-testing": {
    metrics: [["50+", "Otomatik Test Senaryosu"], ["Çok Sensör", "Veri Toplama"], ["Güvenlik Kritik", "Doğrulama"]],
    summary: "50+ otomatik test senaryosu, yük hücresi entegrasyonu, çok sensörlü veri toplama ve güvenlik kritik doğrulama ile hidrolik test sistemi; vagon ve şasi dayanıklılık testleri için düzenleyici uyumlu.",
    body: [["Ne Yaptım", "Tren vagonu ve şasi dayanıklılık testleri için hidrolik test sistemi kurdum. 50+ otomatik test senaryosu geliştirdim; yük hücreleriyle yük ölçümü, basınç sensörleriyle hidrolik basınç izleme uyguladım. Çok sensörlü veri toplama ile gerçek zamanlı kayıt ve analiz sağladım, güvenlik kritik doğrulama ve düzenleyici uyum kontrollerini entegre ettim."]],
    tech: [["Test Altyapısı", ["Hidrolik Sistem", "Yük Hücreleri", "Basınç Sensörleri"]], ["Kontrol", ["PLC", "HMI", "50+ Test Senaryosu"]], ["Veri Toplama", ["Çok Sensör", "Gerçek Zamanlı Kayıt", "Analiz"]], ["Güvenlik", ["Güvenlik Kritik", "Düzenleyici Uyum", "Acil Durdurma"]]],
    highlights: [["Otomatik Test Sekansı", "50+ önceden programlanmış senaryoyla tekrarlanabilir ve doğru test prosedürleri."], ["Yük Hücresi Entegrasyonu", "Çoklu yük hücresiyle vagon ve şasi üzerindeki yük dağılımının doğru ölçümü."], ["Güvenlik Kritik Doğrulama", "Testlerin güvenlik sınırları içinde yürütülmesini sağlayan kapsamlı doğrulama."], ["Düzenleyici Uyum", "Vagon test standartlarına otomatik uygunluk kontrolü."]],
    results: [["Sistem Yetkinlikleri", ["50+ otomatik test senaryosu", "Yük hücreleriyle yük ölçümü", "Çok sensörlü veri toplama ve analiz", "Gerçek zamanlı kayıt ve raporlama"]], ["İş Etkisi", ["Veri kalitesi ve doğruluğunda artış", "Test süresinde azalma", "Düzenleyici uyumun sağlanması", "Belgelenmiş, tekrarlanabilir test prosedürleri"]]],
    gallery: [{"src":"images/projects/wagon-testing-img-01.jpg","label":"VGN-F01"},{"src":"images/projects/wagon-testing-img-02.png","label":"VGN-F02"},{"src":"images/projects/wagon-testing-img-03.png","label":"VGN-F03"}],
    videos: []
  },
  "troubleshooting": {
    metrics: [["30+", "Tesis"], ["Saha", "Teknik Hizmet"], ["Tanı", "Temelli Çözüm"]],
    summary: "Hidrolik makinelerde kablolama hataları, sensör arızaları ve programlama hataları analiz edilip çözüldü. Eski PLC, HMI ve kablolama revize edilerek programlar sıfırdan yazıldı; osiloskop ve multimetre ile sistematik problem çözümü.",
    body: [["Ne Yaptım", "30+ tesiste endüstriyel otomasyon sistemleri için saha teknik servisi verdim. Kablaj arızaları, sensör bozulmaları, programlama hataları ve sistem entegrasyon sorunlarını tespit edip çözdüm. Osiloskop, multimetre ve tanı araçlarıyla sistematik arıza giderme yaklaşımı benimsedim; devreye alma ve ilk kurulum hizmetleri sağladım."]],
    tech: [["Tanı Araçları", ["Osiloskop", "Multimetre", "Programlama Arayüzleri"]], ["Yazılım", ["TIA Portal", "HMI Tanı", "Alarm Analizi"]], ["Yöntem", ["Sistematik Arıza Giderme", "Adım Adım Test"]], ["Hizmet", ["Saha Teknik", "Devreye Alma", "Müşteri Eğitimi"]]],
    highlights: [["Sistematik Tanı", "Osiloskop ve multimetreyle arıza noktasını yalıtan yapılandırılmış problem çözümü."], ["Geniş Tesis Deneyimi", "Farklı otomasyon platformlarında 30+ tesiste saha servisi."], ["Devreye Alma", "Yeni sistem kurulumu, ilk devreye alma, test ve doğrulama prosedürleri."], ["Müşteri Eğitimi", "Operatörler için arıza giderme prosedürleri ve kullanım rehberleri."]],
    results: [["Yaygın Sorun Kategorileri", ["Kablaj ve bağlantı arızaları", "Sensör bozulmaları ve kalibrasyon", "PLC programlama hataları", "Sistem entegrasyon ve iletişim sorunları", "Motor ve sürücü arızaları"]], ["Sonuç", ["Eski PLC/HMI'lerin revizyonu ve program yenileme", "Kesinti sürelerinde belirgin azalma", "Belgelenmiş bakım prosedürleri", "Müşteri ekiplerinin yetkinlik kazanması"]]],
    gallery: [{"src":"images/projects/troubleshooting-img-01.jpg","label":"SRV-F01"},{"src":"images/projects/troubleshooting-img-04.jpg","label":"SRV-F02"},{"src":"images/projects/troubleshooting-img-05.jpg","label":"SRV-F03"},{"src":"images/projects/troubleshooting-img-06.jpg","label":"SRV-F04"},{"src":"images/projects/troubleshooting-img-07.jpg","label":"SRV-F05"}],
    videos: [{"src":"https://kaankirsan.github.io/images/projects/wagon-testing-video-03.mp4","poster":"images/projects/wagon-testing-video-03-poster.jpg","label":"SRV-V01"},{"src":"https://kaankirsan.github.io/images/projects/wagon-testing-video-04.mp4","poster":"images/projects/wagon-testing-video-04-poster.jpg","label":"SRV-V02"},{"src":"https://kaankirsan.github.io/images/projects/troubleshooting-video-01.mp4","poster":"images/projects/troubleshooting-video-01-poster.jpg","label":"SRV-V03"}]
  },
  "resistance-automation": {
    metrics: [["40+", "Sistem Kurulumu"], ["±%1", "Tolerans"], ["%20", "Enerji Azaltma"]],
    summary: "Askeri ve endüstriyel uygulamalar için ±%1 toleranslı PID kontrol sistemleri. Kauçuk işlemede %20 enerji tasarrufu ve yangına dayanıklı tasarım; 40+ sistem kurulumu tamamlandı.",
    body: [["Ne Yaptım", "Askeri ve endüstriyel uygulamalar için rezistans otomasyon sistemleri kurdum. Siemens PLC kullanan ±%1 toleranslı PID kontrol sistemleri tasarladım, kauçuk işleme prosesinde enerji tüketimini %20 azalttım. Yangına dayanıklı tasarımla güvenli çalışma ortamı sağladım; 40+ sistem başarıyla devreye alındı."]],
    tech: [["Kontrol", ["Siemens PLC", "PID Kontrol", "TIA Portal"]], ["Güç Elektroniği", ["Direnç Elemanları", "Transformatörler", "Güç Dağıtımı"]], ["Sıcaklık", ["Termokupl", "RTD Sensörler", "Isı Yönetimi"]], ["Güvenlik", ["Yangına Dayanıklı", "Isı Koruması", "Acil Durdurma"]]],
    highlights: [["Hassas PID Kontrol", "±%1 toleranslı sıcaklık kontrolü sağlayan PID algoritmaları."], ["Enerji Optimizasyonu", "Akıllı ısı yönetimi ve kontrol stratejileriyle kauçuk işlemede %20 enerji tasarrufu."], ["Yangına Dayanıklı Tasarım", "Yüksek ısı ortamlarında güvenli çalışma için dayanıklı malzeme ve tasarım."], ["Askeri Nitelik", "Askeri uygulamalara uygun güvenilirlik ve performans standartları."]],
    results: [["Sistem Performansı", ["±%1 toleranslı sıcaklık kontrolü", "%20 enerji tüketim azaltımı", "40+ sistem kurulumu tamamlandı", "Askeri ve endüstriyel standartlara uyum"]], ["İş Etkisi", ["Enerji maliyetlerinde belirgin azalma", "Üretim kalitesi ve tutarlılığında artış", "Operatör güvenliğinin sağlanması", "Uygulanabilir tasarımla hızlı kurulum"]]],
    gallery: [{"src":"images/projects/resistance-01.jpg","label":"REZ-F01"},{"src":"images/projects/resistance-02.jpg","label":"REZ-F02"}],
    videos: [{"src":"https://kaankirsan.github.io/images/projects/resistance-video-01.mp4","poster":"images/projects/resistance-video-01-poster.jpg","label":"REZ-V01"}]
  },
  "webserver-setup": {
    metrics: [["5+", "Sunucu Kurulumu"], ["%99", "Çalışma Oranı"], ["5 Yıl", "Yönetim Süresi"]],
    summary: "Endüstriyel veri görselleştirme, şirket web siteleri ve özel e-posta sistemleri için 5+ web sunucusu kurulumu. Şirket sitesi beş yıl boyunca %99 çalışma oranında tutuldu; Linux, Docker ve Nginx ile yapılandırma.",
    body: [["Ne Yaptım", "Endüstriyel veri görselleştirme için 5+ web sunucusu kurup yapılandırdım. Şirket web sitesini kurup 5 yıl boyunca %99 çalışma oranında yönettim. Linux üzerinde Docker konteynerleriyle uygulama dağıtımı yaptım, Nginx ile yük dengeleme ve ters vekil yapılandırdım, özel e-posta sistemi kurup SSL/TLS güvenliğini uyguladım."]],
    tech: [["İşletim Sistemi", ["Linux", "Ubuntu", "Sistem Yönetimi"]], ["Konteynerleştirme", ["Docker", "Docker Compose", "Image Yönetimi"]], ["Web Sunucu", ["Nginx", "Yük Dengeleme", "Ters Vekil"]], ["Güvenlik", ["SSL/TLS", "VPN", "Güvenlik Duvarı"]]],
    highlights: [["Endüstriyel Veri Görselleştirme", "Otomasyon verilerinin tarayıcı üzerinden izlenmesi için özel platform."], ["Docker Dağıtımı", "Bağımsızlık ve kolay ölçeklenme için konteyner tabanlı üretim ortamı."], ["Yüksek Erişilebilirlik", "Yük dengeleme, yedekleme ve otomatik yeniden başlatmayla 5 yıl %99 uptime."], ["Güvenli İletişim", "SSL/TLS şifreleme, VPN ile uzaktan erişim ve güvenlik duvarı kuralları."]],
    results: [["Sistem Yetkinlikleri", ["5+ web sunucusu kurulumu ve yönetimi", "Docker konteyner tabanlı dağıtım", "Nginx yük dengeleme ve ters vekil", "Özel e-posta ve uygun maliyetli depolama"]], ["İş Etkisi", ["Endüstriyel verilere web üzerinden erişim", "5 yıl boyunca %99 hizmet sürekliliği", "Google Ads ile makine satışlarında %100 artış", "İç ve dış müşteriler için dijital altyapı"]]],
    gallery: [{"src":"images/projects/webserver-01.jpg","label":"SRVR-F01"},{"src":"images/projects/webserver-02.jpg","label":"SRVR-F02"},{"src":"images/projects/website-01.jpg","label":"SRVR-F03"},{"src":"images/projects/website-02.jpg","label":"SRVR-F04"}],
    videos: []
  },
  "exhibitions-training": {
    metrics: [["3+", "Endüstri Fuarı"], ["PLC", "Programlama Eğitimi"], ["Çok Kültürlü", "Eğitim Oturumları"]],
    summary: "3+ endüstri fuarında teknik sunum, tedarikçi anlaşmalarının sağlanması ve üniversite öğrencilerine PLC programlama eğitimi.",
    body: [["Ne Yaptım", "3+ endüstri fuarında teknik sunum yaptım; ürün ve çözüm sunumlarıyla potansiyel müşteri ve tedarikçilerin ilgisini çektim. Tedarikçi anlaşmalarını müzakere edip sonuçlandırdım. Üniversite öğrencilerine yönelik PLC programlama eğitimleri düzenledim ve çok kültürlü ortamlarda sunum yaptım."]],
    tech: [["Fuarlar", ["Teknik Sunum", "Ürün Tanıtımı"]], ["Eğitim", ["PLC Programlama", "Uygulamalı Atölye", "Öğrenci Eğitimi"]], ["İş Geliştirme", ["Tedarikçi Anlaşmaları", "Müşteri İlişkileri"]], ["Uluslararası", ["Çok Kültürlü İletişim", "Uluslararası Deneyim"]]],
    highlights: [["Teknik Sunum", "Otomasyon çözümlerini farklı teknik seviyedeki kitlelere aktarma."], ["Eğitim", "Üniversite öğrencilerine PLC programlama eğitimi ve uygulamalı atölyeler."], ["İş Geliştirme", "Fuarlarda ürün tanıtımı, müşteri iletişimi ve tedarikçi ilişkileri."], ["Çok Kültürlü İletişim", "Farklı kültürlerden katılımcılarla etkili iletişim."]],
    results: [["Temel Başarılar", ["3+ fuarda başarılı teknik sunum", "Tedarikçi anlaşmalarının sağlanması", "Üniversite öğrencilerine PLC eğitimi", "Ürün tanıtımı ve pazarlama"]]],
    gallery: [{"src":"images/projects/exhibitions-img-01.jpg","label":"FUAR-F01"},{"src":"images/projects/training-01.jpg","label":"FUAR-F02"},{"src":"images/projects/training-02.jpg","label":"FUAR-F03"}],
    videos: []
  },
  "other-machines": {
    metrics: [["30+", "Otomatize Makine"], ["%40", "Verimlilik Artışı"], ["15+", "Üretim Hattı"]],
    summary: "PLC mantık iyileştirmeleri ve HMI geliştirmeleriyle üretim makinelerinde çevrim sürelerini optimize eden çalışmalar. Eski kontrol bileşenleri güncellendi, kablolama revize edildi, hat verimliliği artırıldı.",
    body: [
      ["Zorluk", "Seri üretim tesisleri, farklı makineler için güvenilir ve verimli otomasyon gerektirir. Her makinenin kontrol mantığı, güvenlik sistemleri, operatör arayüzü ve mevcut altyapıyla entegrasyon açısından kendine özgü gereksinimleri vardır."],
      ["Çözüm", "Makine kontrol mantığı, güvenlik kilitleri ve üretim sıralaması için özel PLC programları geliştirdim; gerçek zamanlı görselleştirme, alarm yönetimi ve üretim takibi sunan sezgisel HMI arayüzleri kurdum. Sensör, aktüatör, sürücü ve güvenlik cihazlarını tek bir tutarlı kontrol sisteminde topladım."],
      ["Teknik Yaklaşım", "PLC programlama IEC 61131-3 standartlarına uygun; işlev blokları, durum makineleri ve yapılandırılmış kodla bakımı kolay uygulamalar. Sistem entegrasyonu PLC'leri VFD, servo ve pnömatik sistemlere Modbus, Profinet veya üreticiye özel protokollerle bağlıyor; kapsamlı test, dokümantasyon ve operatör eğitimiyle tamamlanıyor."]
    ],
    tech: [["PLC Sistemleri", ["Siemens S7-1200/1500", "Delta DVP", "Fatek", "Omron CP/NJ"]], ["Programlama & HMI", ["TIA Portal", "WinCC Unified", "Structured Text", "Ladder"]], ["İletişim", ["Modbus RTU/TCP", "Profinet", "Ethernet/IP", "RS232/485"]], ["Sürücüler & Hareket", ["VFD Kontrolü", "Servo Sistemler", "Konumlandırma", "Hız Kontrolü"]]],
    highlights: [["Özel Makine Kontrolü", "Montaj, test, paketleme ve malzeme taşıma dahil 30+ farklı makine için PLC programları."], ["Güvenlik Entegrasyonu", "Acil durdurma, güvenlik PLC'leri, ışık perdeleri ve kilit sistemleriyle mevzuat uyumu."], ["HMI Geliştirme", "Gerçek zamanlı izleme, alarm yönetimi, üretim takibi ve reçete yönetimi."], ["Sistem Optimizasyonu", "Geliştirilmiş mantık, daha iyi sıralama ve azaltılmış çevrim süreleriyle %40 verimlilik artışı."]],
    results: [["Teknik Başarılar", ["30+ makine başarıyla otomatize edildi", "15+ üretim hattında entegre kontrol sistemleri", "Optimizasyonla ortalama %40 verimlilik artışı", "%99.5 çalışma güvenilirliği"]], ["İşletme Etkisi", ["Üretim verimliliğinde belirgin artış", "Operatör iş yükünde azalma", "Ürün kalitesi ve tutarlılığında iyileşme", "Kestirimci izlemeyle düşen bakım maliyetleri"]]],
    gallery: [{"src":"images/projects/other-machines-img-01.jpg","label":"MKN-F01"},{"src":"images/projects/other-machines-img-03.jpg","label":"MKN-F02"},{"src":"images/projects/other-machines-img-04.jpg","label":"MKN-F03"},{"src":"images/projects/other-machines-img-05.jpg","label":"MKN-F04"},{"src":"images/projects/other-machines-img-06.jpg","label":"MKN-F05"},{"src":"images/projects/other-machines-img-07.jpg","label":"MKN-F06"},{"src":"images/projects/other-machines-img-08.png","label":"MKN-F07"},{"src":"images/projects/other-machines-img-09.png","label":"MKN-F08"},{"src":"images/projects/other-machines-img-10.png","label":"MKN-F09"},{"src":"images/projects/other-machines-img-11.png","label":"MKN-F10"},{"src":"images/projects/other-machines-img-12.png","label":"MKN-F11"}],
    videos: [{"src":"https://kaankirsan.github.io/images/projects/wagon-testing-video-01.mp4","poster":"images/projects/wagon-testing-video-01-poster.jpg","label":"MKN-V01"},{"src":"https://kaankirsan.github.io/images/projects/wagon-testing-video-02.mp4","poster":"images/projects/wagon-testing-video-02-poster.jpg","label":"MKN-V02"},{"src":"https://kaankirsan.github.io/images/projects/wagon-testing-video-05.mp4","poster":"images/projects/wagon-testing-video-05-poster.jpg","label":"MKN-V03"},{"src":"https://kaankirsan.github.io/images/projects/wagon-testing-video-06.mp4","poster":"images/projects/wagon-testing-video-06-poster.jpg","label":"MKN-V04"},{"src":"https://kaankirsan.github.io/images/projects/wagon-testing-video-07.mp4","poster":"images/projects/wagon-testing-video-07-poster.jpg","label":"MKN-V05"},{"src":"https://kaankirsan.github.io/images/projects/wagon-testing-video-08.mp4","poster":"images/projects/wagon-testing-video-08-poster.jpg","label":"MKN-V06"},{"src":"https://kaankirsan.github.io/images/projects/wagon-testing-video-10.mp4","poster":"images/projects/wagon-testing-video-10-poster.jpg","label":"MKN-V07"},{"src":"https://kaankirsan.github.io/images/projects/wagon-testing-video-11.mp4","poster":"images/projects/wagon-testing-video-11-poster.jpg","label":"MKN-V08"},{"src":"https://kaankirsan.github.io/images/projects/other-machines-video-01.mp4","poster":"images/projects/other-machines-video-01-poster.jpg","label":"MKN-V09"},{"src":"https://kaankirsan.github.io/images/projects/other-machines-video-02.mp4","poster":"images/projects/other-machines-video-02-poster.jpg","label":"MKN-V10"}]
  },
  "personal-projects": {
    metrics: [["5", "Proje"], ["500W", "Elektrikli Bisiklet"], ["45 km", "Menzil"]],
    summary: "500W elektrikli bisiklet (30 km/h hız, 45 km menzil), ESP32 ev otomasyonu, sosyal medya otomasyon araçları, kişisel NAS cihazı ve 3D baskı projeleri.",
    body: [["Ne Yaptım", "Mesai dışında donanım ve yazılımı bir arada tuttuğum kişisel projeler geliştiriyorum: 500W motor, BMS ve pil paketiyle kurduğum elektrikli bisiklet; ESP32 tabanlı ev otomasyonu; içerik ve sosyal medya için otomasyon araçları; kendi NAS cihazım ve 3D baskıyla ürettiğim mekanik parçalar."]],
    tech: [["Gömülü", ["ESP32", "STM32", "Arduino"]], ["Güç", ["500W BLDC Motor", "Lityum Pil Paketi", "BMS"]], ["Yazılım", ["Python", "Otomasyon Scriptleri", "REST API"]], ["Üretim", ["3D Baskı", "CAD", "Mekanik Montaj"]]],
    highlights: [["Elektrikli Bisiklet", "500W motor, özel pil paketi ve BMS ile 30 km/h hız, 45 km menzil."], ["Ev Otomasyonu", "ESP32 tabanlı sensör ve röle düğümleriyle yerel kontrol."], ["Kişisel NAS", "Ev ağı için depolama ve yedekleme sunucusu."], ["3D Baskı", "Prototip ve mekanik parça üretimi."]],
    results: [["Öne Çıkanlar", ["5 tamamlanmış kişisel proje", "Donanım + yazılım uçtan uca tasarım", "Gerçek kullanımda test edilmiş sistemler"]]],
    gallery: [{"src":"images/projects/personal-img-01.jpg","label":"KSL-F01"},{"src":"images/projects/personal-img-02.jpg","label":"KSL-F02"},{"src":"images/projects/personal-img-03.jpg","label":"KSL-F03"},{"src":"images/projects/personal-img-04.jpg","label":"KSL-F04"},{"src":"images/projects/personal-img-05.jpg","label":"KSL-F05"},{"src":"images/projects/hobbies-02.jpg","label":"KSL-F06"},{"src":"images/projects/personal-img-06.jpg","label":"KSL-F07"},{"src":"images/projects/personal-img-09.jpg","label":"KSL-F08"},{"src":"images/projects/personal-img-07.jpg","label":"KSL-F09"},{"src":"images/projects/personal-img-08.jpg","label":"KSL-F10"},{"src":"images/projects/personal-img-10.jpg","label":"KSL-F11"}],
    videos: [{"src":"https://kaankirsan.github.io/images/projects/personal-video-01.mp4","poster":"images/projects/personal-video-01-poster.jpg","label":"KSL-V01"},{"src":"https://kaankirsan.github.io/images/projects/personal-video-02.mp4","poster":"images/projects/personal-video-02-poster.jpg","label":"KSL-V02"}]
  }
};
